### ISSUE TITLE
Move away from bootstrap

### ISSUE THREAD

**Issue by elliot-a** [slabs-io/slabs#7]
Implement foundation : 

http://foundation.zurb.com/

**Comment by elliot-a** [comment]
I think we should actually stay with bootstrap - and simply re-skin it to look different - all these CSS frameworks are essentially the same. 

Plus there are loads of bootstrap themes we can use.

**Comment by benbrunton** [comment]
:+1:

**Comment by morcmarc** [comment]
+1
